{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "my-plain-secret",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "my-plain-secret",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "password": "AgB6CpB1MiYwv0zO6+sKQtV+l8+PK4rI55MKPVQaM5qm2+uKAzlvx03ACszBCt5ie2NB+0qOeqM0JNzS1xmrUd9RvncV1QJFNODmn88VT9uOb3AOkatSW74JImHCpzcmBTeALw0gDj1fw/BNPZw3uN/oGfHNUyPS/6uxCbwc66B85ik5PoyCAFRP/iOE97Gs/DwMUaUcC4E6XMfXQZXL1RE3qp9LcP8KgKF2D6uPc09Fg77e6KgUba7K6T869jFECk4uKlXR5R+3imI8EVd/0UiduS+ks6BmKJoagkTzHHyYs2K207Rhd5PzMjuVBDXp0UW1j4+4buKywyblnigw8IxRsfyQtUKYwYCIYZCwx8E1759rn8rFj+dEOooKsR4Sh3WsSDTOt48wXnLN0yNviMo2cNCCNbJ/PcHg5ISrzN8t0yz2HEg5bCA6fcJago8AY2ZMi6S91VSsCg6P29brsKRtXfibSKh+IkLZUR++HYSTwOp/qQ9DZArHBspbtj6r9K3H+dmufkfaCNgNq8kuKkD4TAFPdTaijMlb9UYchBhSf7YYYtk0HjqpFP3hq6jpj4qv7NvypwSCCl3NsR/waxP+aBs2b+jhjwHFb84WPYMP12yqTKYX3W+eJbFlanaCGvzgL51wx3q4tDybEUfTWf5n1OQIYKWpr6S8PMbvsb1dZFga5FF3FYNl7KCyDhNszn5bXiu5Ow==",
      "username": "AgAUIY7sRLaUPvSzq6Pk+iRcCtPldkTlGBt2JUSK4d8eGw4CjgVHUMbs+mMcDMfEpuKvJwdGPW2xmB2FqP1fpXPj8cf37uNH1uND2GqXLh1dGB2q2Lqu+EL8jsDXcciodcRA+2sw8M/LJj8l8eliLCWIWJ069FfU/OoafNFi/5WVztz3tq7ghzc7ddeUHQc6Y9KLm8M3HDNmp6D3qRZk2qfNcD55hpmtlTId+T00mQzG3z+dh2KkdC4kvQvRHmbHMvNm+9Bz7UkGRM7m9yspLakgT4dhxPJaJah+CDKzDqYe4SXwbJTr2ySNzHHBpARuUlU+wd9PKLSYbXMNLqxxieWf1u4XfrEF1lbuHUnuCidUZzakDvjUkAKSJCGf+lgLSJL6G2y9I9ugvXnlJPHojNYxNcWn42BZSJPn+j0mdkkwOi8vCEwlk+YUwZm/IYHSYcJhod2s7HbGOCnZsq5KtPzLAtLExaZXejEPVNKgBJ7Dal/OJovcz2AJiclI1fmtSDO9D6dC9RbsQy7Pdk2Fv2n+cFs0QfrzKVffhVGlf0o7I2psvMKkXbYJtr51lKOCB+TzW9bant6JNxFpR/6KcQCtoeA52kIELIzAb2KU9Nr6/VxZf+YY76jlnU/cJ7quIlkibHOD64tEyKTCctHqUdIft/Vv19CpdlFqqtX/zmVFD3AzB2rETCkogveEutinf2t5/LSdRceq"
    }
  }
}
