apiVersion: v1
kind: Service
metadata:
  name: node-secrets-example
  namespace: default
spec:
  selector:
    app: node-secrets-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
