name: Seal Secret

on:
  push:
    branches:
      - main

jobs:
  seal-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for required files
        run: |
          if [ ! -f kubernetes/mysecret.yaml ]; then
            echo "Secret file not found, exiting."
            exit 1
          fi
          if [ ! -f public-cert.pem ]; then
            echo "Public certificate file not found, exiting."
            exit 1
          fi

      - name: Install kubeseal
        run: |
          wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.18.1/kubeseal-linux-amd64 -O kubeseal
          chmod +x kubeseal
          sudo mv kubeseal /usr/local/bin/kubeseal

      - name: Create sealed secret
        run: |
          kubeseal --cert public-cert.pem < kubernetes/mysecret.yaml > kubernetes/mysealedsecret.yaml

      - name: Commit sealed secret
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add kubernetes/mysealedsecret.yaml
          git commit -m "Add sealed secret"
          git push
